services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres-zoomcamp
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  volumes:
    postgres-data:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
